version: '3'

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "playwright-tests"
    volumes:
      - ./playwright-report:/playwright-tests/playwright-report
    environment:
      - HTTP_CREDENTIALS_USERNAME:${HTTP_CREDENTIALS_USERNAME}
      - HTTP_CREDENTIALS_PASSWORD:${HTTP_CREDENTIALS_PASSWORD}
      - CI="true"