name: "Playwright Automated API Tests"

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout to tests repository"
        uses: actions/checkout@v4
      - name: "Copy environment file"
        run: |
          cp ./env/.env.example ./env/.env
      - name: "Run playwright tests"
        run: |
          HTTP_CREDENTIALS_USERNAME=guest HTTP_CREDENTIALS_PASSWORD=welcome2qauto docker-compose run tests npm run-script test:api
      - name: "Copy test report"
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 5