name: "Playwright Automated API Tests"

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout to tests repository"
        uses: actions/checkout@v4
      - name: "Copy environment file"
        run: |
          cp ./env/.env.example ./env/.env
      - name: "Run playwright tests"
        run: |
          HTTP_CREDENTIALS_USERNAME=guest HTTP_CREDENTIALS_PASSWORD=welcome2qauto docker-compose run tests && echo "Tests passed" || echo "Tests failed"
      - name: "Copy test report"
        run: |
          mkdir -p playwright-report
          docker cp playwright-tests:/playwright-tests/playwright-report ./playwright-report || echo "Failed to copy test report"
     
          

